from yacs.config import CfgNode as CN

cfg = CN(
    {
        "exp_name": "",
        "logdir": "/data/cc1547/projects/dreamer/dreamer_pytorch/CC_V3/dreamer_V2",
        "resume": True,
        "resume_ckpt": "",
        "debug": False,
        "seed": 0,
        "run_id": "run_0",
        "total_steps": 1e7,
        "model": "dreamer",
        "slow_update_step": 100,
        "arch": {
            "use_pcont": True,
            "mem_size": 100000,
            "prefill": 50000,
            "H": 17,
            "norm_target": True,
            "norm_reward": True,
            "worker_only": False,
            "actor": {
                "num_units": 400,
                "act": "elu",
                "init_std": 5.0,
                "dist": "onehot",
                "layers": 4,
                "aggregator": "none",
                "actor_loss_type": "both",
                "norm": "none",
            },
            "value": {
                "num_units": 400,
                "act": "elu",
                "dist": "normal",
                "layers": 4,
                "norm": "none",
            },
            "world_model": {
                "norm": "none",
                "reward_layer": 4,
                "q_emb_action": False,
                "act_after_emb": False,
                "rec_sigma": 1.0,
                "anneal_world_model": False,
                "discrete_type": "discrete",
                "std_type": "sigmoid2",
                "temp_start": 2.0,
                "temp_end": 0.001,
                "temp_decay_steps": 1e6,
                "RSSM": {
                    "act": "elu",
                    "weight_init": "xavier",
                    "stoch_size": 32,
                    "stoch_discrete": 32,
                    "deter_size": 600,
                    "hidden_size": 600,
                    "rnn_type": "LayerNormGRU",
                    "ST": True,
                    "post_no_deter": False,
                },
                "reward": {
                    "num_units": 400,
                    "act": "elu",
                    "dist": "normal",
                    "layers": 4,
                    "norm": "none",
                },
                "pcont": {
                    "num_units": 400,
                    "dist": "binary",
                    "act": "elu",
                    "layers": 4,
                    "norm": "none",
                },
            },
            "decoder": {"dec_type": "conv",},
            "manager": {
                "K": 8,
                "cum_intri": True,
                "learn_vae_std": True,
                "actor": {
                    "num_units": 512,
                    "act": "elu",
                    "norm": "layernorm",
                    "init_std": 5.0,
                    "dist": "onehot",
                    "layers": 4,
                    "aggregator": "none",
                    "action_num": 8,
                    "action_size": 8,
                    "include_deter": False,
                },
                "intri_value": {
                    "num_units": 512,
                    "act": "elu",
                    "norm": "layernorm",
                    "dist": "normal",
                    "layers": 4,
                },
                "extri_value": {
                    "num_units": 512,
                    "act": "elu",
                    "norm": "layernorm",
                    "dist": "normal",
                    "layers": 4,
                },
            },
        },
        "loss": {
            "pcont_scale": 5.0,
            "kl_scale": 0.1,
            "free_nats": 0.0,
            "kl_balance": 0.8,
            "ent_scale": 1e-3,
            "mgr_exp": 0.1,
            "mgr_extr": 1.0,
        },
        "env": {
            "action_size": 18,
            "name": "atari_boxing",
            "action_repeat": 4,
            "max_steps": 1000,
            "life_done": True,
            "precision": 16,
            "time_limit": 1000,
            "time_penalty": False,
            "grayscale": False,
            "all_actions": True,
            "env_file": "",
            "num_actor": 4,
        },
        "rl": {
            "discount": 0.999,
            "lambda_": 0.95,
            "expl_amount": 0.4,
            "expl_decay": 200000.0,
            "expl_min": 0.1,
            "expl_type": "epsilon_greedy",
            "r_transform": "tanh",
        },
        "data": {
            "datadir": "/data/cc1547/projects/dreamer/dreamer_pytorch/CC_V3/dreamer_V2",
        },
        "train": {
            "batch_length": 50,
            "batch_size": 50,
            "train_steps": 50,
            "train_every": 16,
            "print_every_step": 1000,
            "log_every_step": 1e4,
            "checkpoint_every_step": 1e4,
            "eval_every_step": 1e5,
            "n_sample": 10,
            "imag_last_T": False,
            "log_grad": False,
        },
        "optimize": {
            "warmup_iter": 4e3 * 16,
            "exp_rate": 0.5,
            "decay_step": 1e5 * 16,
            "base_lr": 2e-4,
            "end_lr": 1e-4,
            "model_lr": 2e-4,
            "value_lr": 1e-4,
            "actor_lr": 1e-5,
            "goal_vae_lr": 1e-4,
            "mgr_value_lr": 1e-4,
            "mgr_actor_lr": 1e-4,
            "optimizer": "adamW",
            "grad_clip": 100.0,
            "eps": 1e-5,
            "weight_decay": 1e-6,
            "reward_scale": 1.0,
            "discount_scale": 5.0,
        },
        "checkpoint": {
            "checkpoint_dir": "/data/cc1547/projects/dreamer/dreamer_pytorch/CC_V3/dreamer_V2",
            "max_num": 3,
        },
    }
)

